// <auto-generated />
using System;
using CodeFirstDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221128135917_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstDemo.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasTheForce")
                        .HasColumnType("bit");

                    b.Property<int>("HomePlanetId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDarkSide")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.HasIndex("HomePlanetId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            FirstName = "Luke",
                            HasTheForce = true,
                            HomePlanetId = 1,
                            IsDarkSide = false,
                            LastName = "Skywalker",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 2,
                            FirstName = "Obi-Wan",
                            HasTheForce = true,
                            HomePlanetId = 3,
                            IsDarkSide = false,
                            LastName = "Kenobi",
                            Species = "Human"
                        });
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanetId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            PlanetId = 1,
                            Name = "Tatooine"
                        },
                        new
                        {
                            PlanetId = 2,
                            Name = "Dagobah"
                        },
                        new
                        {
                            PlanetId = 3,
                            Name = "Stewjon"
                        });
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Spaceship", b =>
                {
                    b.Property<int>("SpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceshipId"));

                    b.Property<bool?>("HasHyperDrive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("SpaceshipId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Character", b =>
                {
                    b.HasOne("CodeFirstDemo.Models.Planet", "HomePlanet")
                        .WithMany("NativeCharacters")
                        .HasForeignKey("HomePlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomePlanet");
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Spaceship", b =>
                {
                    b.HasOne("CodeFirstDemo.Models.Character", "Owner")
                        .WithMany("Spaceships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Character", b =>
                {
                    b.Navigation("Spaceships");
                });

            modelBuilder.Entity("CodeFirstDemo.Models.Planet", b =>
                {
                    b.Navigation("NativeCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
